### ISSUE TITLE
Feature Request: Add flag in `moni mems` to output also the position in the reference of the MEM.

### ISSUE THREAD

**Issue by maxrossi91** [maxrossi91/moni#1]
It would be nice to have a flag that outputs the position of a MEM in the reference, in addition to the position in the query and the length.

**Comment by shenwei356** [comment]
And adding the reference name(s) would be perfect.

**Comment by brunelloandrea** [comment]
Has this been implemented?

Thank you.

**Comment by maxrossi91** [comment]
Not yet. I will see if I can implement it in the next days.

**Comment by maxrossi91** [comment]
Included in #6 available in the v0.2.1 release under the `-e` flag when invoking `moni mems`.

**Comment by brunelloandrea** [comment]
Thank you!

Andrea
________________________________
Da: Massimiliano Rossi ***@***.***>
Inviato: Monday, August 5, 2024 10:22:00 PM
A: maxrossi91/moni ***@***.***>
Cc: Andrea Brunello ***@***.***>; Comment ***@***.***>
Oggetto: Re: [maxrossi91/moni] Feature Request: Add flag in `moni mems` to output also the position in the reference of the MEM. (Issue #1)


Closed #1<https://github.com/maxrossi91/moni/issues/1> as completed.
